apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
  - image: ghcr.io/ikenom/vendor-frontend
    sync:
        infer:
        - 'src/**/*'

deploy:
  helm:
    releases:
    - name: gatsby
      artifactOverrides:
        image: ghcr.io/ikenom/vendor-frontend
      chartPath: chart
      skipBuildDependencies: false
      valuesFiles:
        - ./chart/values.yaml
      imageStrategy:
        helm: {}
      createNamespace: true
