apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
  - image: ghcr.io/ikenom/gatsby-dev
    sync:
        infer:
        - 'src/**/*'

deploy:
  helm:
    releases:
    - name: gatsby
      artifactOverrides:
        image: ghcr.io/ikenom/gatsby-dev
      chartPath: charts/gatsby
      skipBuildDependencies: false
      valuesFiles:
        - ./charts/gatsby/values.yaml
      imageStrategy:
        helm: {}
      createNamespace: true
